name: turbo_express
description: A news Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  basic_utils: any
  bloc: ^6.1.1
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.0
  currency_text_input_formatter: ^2.0.0
  cool_ui: ^1.0.1
  dio: ^3.0.0
  easy_localization: ^2.3.3
  equatable: ^0.1.6
  flutter_bloc: ^6.1.1
  flutter_cache_manager: ^2.1.1
  flutter_masked_text: ^0.8.0
  flutter_screenutil: ^4.0.3+1
  flutter_svg: any
  font_awesome_flutter: ^8.11.0
  formz: ^0.2.0
  hive: any
  hive_flutter: any
  image_picker: ^0.6.7+22
  intl: ^0.17.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  meta: ^1.1.6
  path_provider: any
  provider: ^4.3.2+3
  shimmer: ^2.0.0
  sliding_up_panel: ^1.0.2
  shared_preferences: any
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Kraftfahrzeugkennzeichen
      fonts:
        - asset: assets/fonts/kraftfahrzeugkennzeichen.ttf
